### ISSUE TITLE
Can't run console, rake spec, etc.

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/ruby-rnp#4]
# Steps to reproduce
Clone this repo, run `bin/setup`, then `bin/console`.

# Expectation
It should give me a working Ruby console.

#  What actually happens
After cloning this repo and running `bin/setup` and `bin/console`, it's giving me the following error:

```
/Users/username/share/src/ruby-rnp/lib/rnp/lowlevel/librnp.rb:1:in `require': cannot load such file -- ffi (LoadError)
	from /Users/username/share/src/ruby-rnp/lib/rnp/lowlevel/librnp.rb:1:in `<top (required)>'
	from /Users/username/share/src/ruby-rnp/lib/rnp/lowlevel.rb:1:in `require_relative'
	from /Users/username/share/src/ruby-rnp/lib/rnp/lowlevel.rb:1:in `<top (required)>'
	from /Users/username/share/src/ruby-rnp/lib/rnp.rb:3:in `require_relative'
	from /Users/username/share/src/ruby-rnp/lib/rnp.rb:3:in `<top (required)>'
	from bin/console:4:in `require'
	from bin/console:4:in `<main>'
```

So I tried adding `ffi` as one of the dependencies in `rnp.gemspec`, ran `bin/setup`.  Now it's complaining about `FFI::NotFoundError`:
```
/Users/username/.rbenv/versions/2.4.0/bin/ruby -I/Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib:/Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-support-3.5.0/lib /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:275:in `attach_function': Function 'pgp_parse_options' not found in [librnp.dylib] (FFI::NotFoundError)
	from /Users/username/share/src/ruby-rnp/lib/rnp/lowlevel/librnp.rb:10:in `<module:LibRNP>'
	from /Users/username/share/src/ruby-rnp/lib/rnp/lowlevel/librnp.rb:6:in `<top (required)>'
	from /Users/username/share/src/ruby-rnp/lib/rnp/lowlevel.rb:1:in `require_relative'
	from /Users/username/share/src/ruby-rnp/lib/rnp/lowlevel.rb:1:in `<top (required)>'
	from /Users/username/share/src/ruby-rnp/lib/rnp.rb:3:in `require_relative'
	from /Users/username/share/src/ruby-rnp/lib/rnp.rb:3:in `<top (required)>'
	from /Users/username/share/src/ruby-rnp/spec/highlevel/encrypt_decrypt_spec.rb:1:in `require'
	from /Users/username/share/src/ruby-rnp/spec/highlevel/encrypt_decrypt_spec.rb:1:in `<top (required)>'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
/Users/username/.rbenv/versions/2.4.0/bin/ruby -I/Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib:/Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-support-3.5.0/lib /Users/username/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

Any idea how to make it work?  Thanks!

cc: @dewyatt

**Comment by dewyatt** [comment]
This made me realize an issue, fixed in ae152cf6, so this should be good now.
